#!/bin/bash
set -e

# supervise mysql server start
cat > /etc/supervisor/conf.d/mysqld.conf <<EOF
[program:mysqld]
priority=20
directory=/tmp
command=/usr/bin/mysqld_safe
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

echo ""
echo "*************************************************************************"
echo "* Please login to the mysql server and create the required database and *"
echo "* database user with remote login access so that other containers can   *"
echo "* use it.                                                               *"
echo "*                                                                       *"
echo "* e.g.                                                                  *"
echo "*   CREATE DATABASE db_name;                                            *"
echo "*   CREATE USER 'db_user'@'%' IDENTIFIED BY 'db_password';              *"
echo "*   GRANT ALL ON DATABASE.* to 'db_user'@'%';                           *"
echo "*   FLUSH PRIVILEGES;                                                   *"
echo "*************************************************************************"
echo ""
